version: "3.7"
services:
  web:
    image: perhamm/nginx
    container_name: web
    depends_on:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./index.php:/usr/share/nginx/html/index.php
    ports:
      - "80:80"
    networks:
      front_net:
        ipv4_address: 10.20.30.10
        aliases:
          - web


  php:
    image: perhamm/php-fpm
    container_name: php
    volumes:
      - ./index.php:/usr/share/nginx/html/index.php
    networks:
      front_net:
        ipv4_address: 10.20.30.20
        aliases:
          - php


networks:
  front_net:
    ipam:
      config:
        - subnet: "10.20.30.0/24"
