---
- name: Add users and set pam 
  hosts: web
  become: yes

    
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
        
    - name: disable ssl for repo epel
      lineinfile: 
        dest: /etc/yum.repos.d/epel.repo
        insertafter: 'enabled=1' 
        line: 'sslverify=0'

        
    - name: install rpm nginx
      yum:
        name: nginx
        validate_certs: no
        state: present
      notify:
      - restart nginx
      
    - name: install rpm audispd-plugins
      yum:
        name: audispd-plugins
        validate_certs: no
        state: present
      notify:
      - restart nginx

    - name: change nginx conf
      copy: 
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify:
      - restart nginx

    - name: start nginx
      service:
        name: nginx
        enabled: yes
        state: started

    - name: change rsyslog config on web
      copy: 
        src: web-rsyslog.conf
        dest: /etc/rsyslog.conf
        owner: root
        group: root
        mode: '0644'
      notify:
      - restart rsyslog
      
    - name: start rsyslog
      service:
        name: rsyslog
        enabled: yes
        state: started

    - name: change auditd
      copy: 
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: '0640'
      with_items:
        - { src: 'web-audit.rules', dest: '/etc/audit/rules.d/audit.rules' }
        - { src: 'web-audisp-remote.conf', dest: '/etc/audisp/audisp-remote.conf' }
        - { src: 'web-au-remote.conf', dest: '/etc/audisp/plugins.d/au-remote.conf' } 
        - { src: 'web-auditd.conf', dest: '/etc/audit/auditd.conf' }
      notify:
      - setup auditd

  handlers:
  - name: restart nginx
    service:
      name: nginx
      enabled: yes
      state: restarted
  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted
  - name: setup auditd
    shell: |
      systemctl daemon-reload
      service auditd restart