---
# vars file for ansible-mariadb-galera-haproxy-keepalived

keepalived:
  interface: eth2
  virtual_router_id: 71
  priority: 100
  advert_int: 1
  auth_pass: 1111
  virtual_ip: 192.168.62.100/24

haproxy:
  frontend_port: 80
  backend_host:
    - id: 1
      host: 192.168.63.9
      port: 80
    - id: 2
      host: 192.168.63.10
      port: 80
  stats:
    port: 9000
    user: admin
    pass: password
