---
# vars file for ansible-mariadb-galera-haproxy-keepalived

keepalived:
  interface: eth1
  virtual_router_id: 61
  priority: 100
  advert_int: 1
  auth_pass: 1111
  virtual_ip: 192.168.63.15/24

haproxy:
  frontend_port: 4306
  backend_host:
    - id: 1
      host: 192.168.63.1
      port: 3306
    - id: 2
      host: 192.168.63.2
      port: 3306
    - id: 3
      host: 192.168.63.3
      port: 3306
  stats:
    port: 9000
    user: admin
    pass: password
