---
- name: install redhat dependencies
  package:
    name: "{{ redhat_package_dependencies }}"
    state: present
  register: result
  until: result is succeeded
  when: ansible_distribution == 'RedHat'

- name: install centos dependencies
  yum:
    name: "{{ centos_package_dependencies }}"
    state: present
  register: result
  until: result is succeeded
  when: ansible_distribution == 'CentOS'
  
- name: disable ssl for repo epel
  lineinfile: 
    dest: /etc/yum.repos.d/epel.repo
    insertafter: 'enabled=1' 
    line: 'sslverify=0'
  register: result
  until: result is succeeded
  when: ansible_distribution == 'CentOS'


- name: install redhat ceph packages
  package:
    name: "{{ redhat_ceph_pkgs | unique }}"
    state: "{{ (upgrade_ceph_packages|bool) | ternary('latest','present') }}"
  register: result
  until: result is succeeded
